### ISSUE TITLE
How to override holidays

### ISSUE THREAD

**Issue by MathijsK93** [holidays/holidays#116]
We're using the holidays gem to prevent performing actions on holidays, but some holidays defined in the yaml files, such as liberation day, is an normal working day.

I know how to add custom holidays, but how can i override a specific holiday?

**Comment by espen** [comment]
If the day is a working day in your country it should be listed as informal in the data files, right? If you can document this is correct then I suggest you send a pull request.

**Comment by ptrimble** [comment]
@MathijsK93 Yep, @espen had the right of it. If you have documentation (wikipedia, some government site, etc) that the definition is wrong then we can discuss it or you can submit a PR with the update. That would be the best course of action. So, for example, if the day you specified is a holiday but not observed as a day off then we should probably update the defs to make it 'informal'.

As for overriding I don't believe we have the ability to do that. We assume that the definitions represent truth. I'll see what happens when you try to load a 'custom' holiday for an existing date. I've never personally tried.

**Comment by MathijsK93** [comment]
I created an Pull request for this: #126
