### ISSUE TITLE
Support Japanese rokuyo

### ISSUE THREAD

**Issue by johnnyshields** [holidays/holidays#121]
In Japan there is a Buddhist calendar system called "rokuyo". More info here: http://www.seiyaku.com/customs/rokuyo.php. It is standard to see Rokuyo on most calendars printed in Japan.

The logic is complex but essentially each day has a rokuyo day which is one of 6 values, and unlike western weekdays (mon, tues, weds) they don't follow a consistent cycle and reset based on lunar month and other exceptions.

I'd like to make a new "rokuyo" file; if that's cool I'll raise a PR in the next month.

**Comment by ptrimble** [comment]
Yeah, that sounds great. I'm not familiar with it at all (which is hardly surprising, I guess, since I'm in the US) but I'd love to take a look at the PR. I'll leave this issue open for discussion until the PR comes through. 

I'm not entirely sure how I would want to handle something like this...the current standard is for the definition files to equate to regions or areas. This would be a new calendar type instead. I'm not against this plan, really, I just need to think about it and talk it over a bit once the PR is out there. I'll also think about this for the refactoring that I'm doing. There is nothing saying that we need to keep the current meaning of 'definition' files as they are today.

Thanks!

**Comment by johnnyshields** [comment]
@ptrimble just did a brief investigation of the definition file and seems it won't work for the above requirement. The way the file is structure it assumes holidays occur once a year, but for this the same value may occur ~70 times a year.

**Comment by johnnyshields** [comment]
Did a bit more investigation and determined that if you know the Chinese Lunar calendar date there's straightforward logic to calculate the Rokuyo day. (To know the Chinese Lunar new year you need to store some sort of lookup table such as in this gem: https://github.com/lanvige/chinese_lunar)

In short I think Chinese Lunar calendar and Rokuyo this is probably better suited for it's own gem, not Holidays.

**Comment by ptrimble** [comment]
Gotcha! Feel free to ping me if you would like support or reviews, I'd be happy to investigate. Now that we own this 'holidays' org it might make sense to bundle some things together. Who knows!

I'm going to go ahead and close this. Thanks again!
