### ISSUE TITLE
NYSE - Incorrect date for Independence day?

### ISSUE THREAD

**Issue by jasonirwin** [holidays/holidays#125]
This year the 4th of July falls on a Saturday and is observed on Friday 3rd. However, when I run the following, the 4th is still listed as a holiday

```y Holidays.between(Date.civil(2015,1,1),Date.civil(2015,12,31),:nyse)```

Similarly the following returns false:

```d = Date.civil(2015,7,3)
d.holiday?(:nyse)```

If this is a bug I'll be happy to investigate and supply a fix, but I want to confirm that I'm not missing part of the puzzle.
Thanks
Jason

**Comment by ptrimble** [comment]
Hi Jason, thanks for reporting and sorry for the delay, I'll take a look at this on my train ride home this evening and report back with what I find. Then we can make a plan on how to proceed.

**Comment by ptrimble** [comment]
Nope, jumped the gun on the 'bug' designation. I thought I found something but it turns out that I didn't read further. :smile:

The issue here is that this is considered an 'observed' holiday and as such is not automatically returned unless you explicitly pass in the `:observed` flag, like so:

```ruby
d = Date.civil(2015, 7, 3)
Holidays.on(d, :nyse, :observed)
```

The def used the :observed key for this: https://github.com/holidays/holidays/blob/master/data/nyse.yaml#L35

I'm not sure how I feel about :observed not being on 'by default' but I think it can be open to interpretation. I'll have to think about it.

Either way, does this work for you?

**Comment by jasonirwin** [comment]
It certainly does, thanks for the clarification.
