### ISSUE TITLE
how to use Holidays.load_all?

### ISSUE THREAD

**Issue by bluekite17** [holidays/holidays#217]
> RAILS_ENV=production rake redmine:plugins:migrate
rake aborted!
NoMethodError: undefined method `load_all' for Holidays:Module

installed:
ruby-2.3.1/gems/holidays-4.6.0

not found method 'load_all' in 'ruby-2.3.1/gems/holidays-4.6.0/lib/holidays.rb'

**Comment by ptrimble** [comment]
Hi @bluekite17, this method was removed from the public API in version 4 of the gem. It was never really intended for public use and was only available because of a misunderstanding on how class methods interact with the `private` keyword. 

I see now that it is shown in the comments in `lib/holidays.rb` and I will remove it to make it more clear that it is not around anymore. Sorry about that.

Can you help me understand what you are trying to do? With version 4 and up of this gem we already 'require' all of the available generated definitions upon `require 'holidays'`. See here: https://github.com/holidays/holidays/blob/master/lib/holidays/load_all_definitions.rb

As far as I am aware this results in the same requiring of all of the generated definitions that the old `load_all` method did. If you are seeing that this is not the case then please let me know and outline what your use case is so we can discuss possible solutions.

Thanks!

**Comment by bluekite17** [comment]
Oh.. i see.

Thanks for answer :)
