### ISSUE TITLE
Is there a way to lazily load only the regions I want?

### ISSUE THREAD

**Issue by ghiculescu** [holidays/holidays#221]
Requiring the holidays gem in full via Gemfile takes a fair bit of memory for what it is. (using [`derailed`](https://github.com/schneems/derailed_benchmarks#memory-used-at-require-time))

```
  holidays: 5.3203 MiB
    /Users/alex/.rvm/gems/ruby-2.2.3/bundler/gems/holidays-de23f5924f9a/lib/holidays/../generated_definitions/europe.rb: 0.9844 MiB
    holidays/factory/definition: 0.707 MiB
    holidays/factory/finder: 0.4453 MiB
```

It would be good to be able to only require regions you need. For example, I only care about `['au', 'jp', 'nz', 'za', 'gb', 'us']` so it would be great if I could do this in my Gemfile:

```
gem 'holidays', require: false
```

and then this in an initializer:

```
require 'holidays'
['au', 'jp', 'nz', 'za', 'gb', 'us'].each {|region| require "holidays/definitions/#{region}"}
```

based on my current reading of the gem it seems like https://github.com/holidays/holidays/blob/master/lib/holidays/load_all_definitions.rb gets run at require-time which seems to make this optimisation impossible.

@ptrimble am I reading this right? Do you have any ideas on how we could make this happen (or if it's even worth doing)?

**Comment by ptrimble** [comment]
Sorry for the delay, I just moved into my new house. 😄 

Yes, you are! I made this change in the last major version bump. To be honest it was at the end of a huge refactoring bent and I just...made the call to do it to get over the hump. I 100% agree that lazy loading is more efficient.

Let me think about this for a bit. Now that I have some time and perspective I might have other solutions that will make it easier.

**Comment by ptrimble** [comment]
Soo.....this turned out to be easier than I thought. The refactoring that has been done makes this a lot safer to do. Check out my PR: https://github.com/holidays/holidays/pull/222

This will bring back the lazy loading with no outward change to users. I don't think anyone really cared about whether it was lazy loaded or not so I don't mind making this change.

I remember why I did this originally: I was not happy with the 'on the fly' requiring of files. But I believe that with the latest validation work we've done we're protected. If a malicious region is provided we'll catch it.

What do you think? I'll test it out with the `derailed` gem shortly.

**Comment by ghiculescu** [comment]
looks awesome @ptrimble (minus the red build)

**Comment by ptrimble** [comment]
Thanks Alex! I'll merge this ASAP. Please hang tight while I add in some other stuff that I want to do with the major version bump. I'm trying to knock out a few things that I wanted to do on the next major version bump so I'll bundle a few together at once. 😄
